'use client'

import Image from 'next/image'
import { ArrowRight, Clock3, ExternalLink, MapPin, Menu as MenuIcon, Phone, ShoppingBag, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { copy, gallery, mapSearch, menu, site, type Locale } from '@/lib/site-data'

const external = { target: '_blank', rel: 'noopener noreferrer' as const }

export default function HomePage({ locale = 'ru' }: { locale?: Locale }) {
  const [open, setOpen] = useState(false)
  const t = copy[locale]
  useEffect(() => { document.documentElement.lang = t.lang }, [t.lang])
  const structuredData = { '@context': 'https://schema.org', '@type': 'Restaurant', name: 'Star Burger', address: { '@type': 'PostalAddress', streetAddress: "Jizzax, Madaniyat MFY, Qodirjon Inomov ko‘chasi, 73", addressLocality: 'Jizzax', addressCountry: 'UZ' }, telephone: '+998955033333', openingHours: 'Mo-Su 00:00-24:00', priceRange: '$$', servesCuisine: ['Burgers', 'Pizza', 'Turkish', 'Grill'], sameAs: [site.googleMaps, site.yandexMaps, site.telegram, site.instagram] }
  return <main className="min-h-screen overflow-x-hidden bg-[#111110] pb-20 text-[#f3efe6] md:pb-0"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#111110]/90 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#top" className="flex items-center gap-3 focus-visible:outline-2 focus-visible:outline-[#b7d33a]"><Image src="/images/logo.png" alt="Star Burger" width={42} height={42} className="h-10 w-10 object-contain"/><span className="font-bold tracking-[.18em]">STAR BURGER</span></a><nav className="hidden items-center gap-7 text-sm font-semibold md:flex"><a href="#menu">{t.menu}</a><a href="#about">{t.about}</a><a href="#reviews">{t.reviews}</a><a href="#contact">{t.contact}</a><a href={site.tel} className="flex items-center gap-2 text-[#b7d33a]"><Phone size={16}/> {t.contact}</a><div className="flex gap-2 border-l border-white/20 pl-5">{(['ru','uz','en'] as Locale[]).map(l => <a key={l} href={`/${l}`} aria-current={l === locale ? 'page' : undefined} className={l === locale ? 'text-[#b7d33a]' : 'text-[#f3efe6]/60'}>{l.toUpperCase()}</a>)}</div></nav><button aria-label={open ? 'Закрыть меню' : 'Открыть меню'} aria-expanded={open} onClick={() => setOpen(!open)} className="rounded p-2 focus-visible:outline-2 focus-visible:outline-[#b7d33a] md:hidden">{open ? <X/> : <MenuIcon/>}</button></div>{open && <nav className="flex flex-col gap-5 border-t border-white/10 bg-[#111110] px-5 py-6 md:hidden"><div className="flex gap-5 font-bold">{(['ru','uz','en'] as Locale[]).map(l => <a key={l} href={`/${l}`} className={l === locale ? 'text-[#b7d33a]' : ''}>{l.toUpperCase()}</a>)}</div><a href="#menu" onClick={() => setOpen(false)}>{t.menu}</a><a href="#about" onClick={() => setOpen(false)}>{t.about}</a><a href="#reviews" onClick={() => setOpen(false)}>{t.reviews}</a><a href="#contact" onClick={() => setOpen(false)}>{t.contact}</a></nav>}</header>
    <section id="top" className="relative isolate flex min-h-[720px] items-center overflow-hidden px-5 pb-20 pt-32 lg:min-h-[820px] lg:px-8"><Image src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_4558.JPG-7usfR6YFj0uwyQqns5DDldP17PqPuf.jpeg" alt="Fresh Star Burger burger" fill priority sizes="100vw" className="object-cover object-[68%_center] opacity-80" unoptimized/><div className="absolute inset-0 -z-10 bg-[#111110]"/><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,#111110_0%,#111110e8_28%,#11111080_53%,#11111015_100%)]"/><div className="absolute inset-0 -z-10 bg-[linear-gradient(0deg,#111110cc_0%,transparent_34%,#11111033_100%)]"/><div className="relative mx-auto w-full max-w-7xl"><div className="max-w-xl"><p className="mb-6 flex items-center gap-3 text-xs font-bold uppercase tracking-[.28em] text-[#b7d33a]"><span className="h-2 w-2 rounded-full bg-[#b7d33a]"/> {t.city}</p><h1 className="serif text-balance text-5xl leading-[.92] tracking-[-.06em] sm:text-6xl md:text-8xl lg:text-9xl">{t.hero[0]}<br/><em className="text-[#f26722]">{t.hero[1]}</em><br/>{t.hero[2]}</h1><p className="mt-7 max-w-sm text-base leading-6 text-[#f3efe6]/75">{t.intro}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={site.menuUrl} {...external} className="flex items-center justify-center gap-3 bg-[#f26722] px-6 py-4 font-bold text-[#111110] shadow-[0_12px_40px_#f2672240] transition hover:bg-[#b7d33a]">{t.viewMenu} <ArrowRight size={18}/></a><a href={site.telegram} {...external} className="flex items-center justify-center gap-3 border border-[#f3efe6]/40 bg-[#111110]/20 px-6 py-4 font-bold backdrop-blur-sm transition hover:border-[#b7d33a]">{t.order}</a></div></div></div></section>
    <section className="border-y border-white/10 bg-[#f3efe6] text-[#111110]"><div className="mx-auto grid max-w-7xl grid-cols-5 items-center gap-1 px-3 py-5 text-center text-xs font-bold uppercase tracking-[.08em] sm:gap-3 sm:px-5 sm:text-sm sm:tracking-[.12em] lg:px-8"><span>Бургеры</span><span>Пицца</span><span>Лаваш</span><span>Гриль</span><span>Завтраки</span></div></section>
    <section id="menu" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-[#b7d33a]">{t.kitchen}</p><h2 className="serif text-5xl tracking-[-.04em] md:text-7xl">{t.hits}</h2></div><a href={site.menuUrl} {...external} className="flex w-fit items-center gap-2 border-b border-[#f26722] pb-2 font-bold text-[#f26722]">{t.fullMenu} <ArrowRight size={16}/></a></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{menu.map((item, i) => <article key={item.name} className="group"><div className="relative aspect-[4/3] overflow-hidden bg-[#252523]"><Image src={item.image} alt={item.name} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-3 top-3 bg-[#b7d33a] px-3 py-1 text-xs font-black uppercase text-[#111110]">{i === 0 ? 'Hit' : 'Star'}</span></div><div className="flex items-start justify-between gap-3 border-b border-white/15 py-4"><div><h3 className="text-xl font-bold">{item.name}</h3><p className="mt-1 text-sm text-[#a5a39c]">{item.desc}</p></div><strong className="whitespace-nowrap text-[#f26722]">{item.price}</strong></div></article>)}</div></section>
    <section id="about" className="bg-[#b7d33a] px-5 py-20 text-[#111110] lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_1.2fr] lg:items-end"><div><p className="mb-3 text-sm font-black uppercase tracking-[.2em]">Star Burger</p><h2 className="serif text-5xl leading-none tracking-[-.04em] md:text-7xl">{t.always}</h2></div><div className="grid gap-6 sm:grid-cols-3"><div><Clock3 size={27}/><h3 className="mt-4 text-lg font-bold">24/7</h3><p className="mt-2 text-sm leading-5">{t.open}</p></div><div><ShoppingBag size={27}/><h3 className="mt-4 text-lg font-bold">{t.private}</h3></div><div><MapPin size={27}/><h3 className="mt-4 text-lg font-bold">{t.football}</h3></div></div></div></section>
    <section id="reviews" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-[#b7d33a]">{t.reviews}</p><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><h2 className="serif text-5xl tracking-[-.04em] md:text-7xl">{t.reviews}</h2><div className="flex flex-wrap gap-3"><a href={site.googleReviews} {...external} className="border border-white/20 px-4 py-3 text-sm font-bold hover:border-[#b7d33a]">Отзывы в Google</a><a href={site.yandexReviews} {...external} className="border border-white/20 px-4 py-3 text-sm font-bold hover:border-[#b7d33a]">Отзывы в Яндекс Картах</a></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="border border-white/10 bg-[#1b1b19] p-5"><p className="text-[#a5a39c]">Google · 4,3</p><p className="mt-3 text-sm text-[#a5a39c]">Реальные отзывы доступны в официальной карточке заведения.</p></div><div className="border border-white/10 bg-[#1b1b19] p-5"><p className="text-[#a5a39c]">Яндекс · 4,9</p><p className="mt-3 text-sm text-[#a5a39c]">Читайте ��одтверждённые отзывы гостей по ссылке.</p></div></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8"><div className="mb-8 flex items-end justify-between"><h2 className="serif text-5xl tracking-[-.04em] md:text-7xl">{t.atmosphere}</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{gallery.map(([src, alt]) => <div key={src} className="relative aspect-[4/3] overflow-hidden"><Image src={src} alt={alt} fill loading="lazy" sizes="(max-width: 640px) 100vw, 33vw" className="object-cover transition duration-500 hover:scale-105"/></div>)}</div></section>
    <section id="contact" className="mx-auto grid max-w-7xl gap-8 px-5 py-20 lg:grid-cols-2 lg:px-8 lg:py-28"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-[#b7d33a]">{t.find}</p><h2 className="serif text-5xl tracking-[-.04em] md:text-7xl">{t.find}</h2><div className="mt-8 space-y-4 text-[#a5a39c]"><p className="flex gap-3"><MapPin className="shrink-0 text-[#f26722]"/> {t.address}</p><p className="flex gap-3"><Clock3 className="shrink-0 text-[#f26722]"/> {t.open}</p><p className="flex gap-3"><Phone className="shrink-0 text-[#f26722]"/> <a href={site.tel}>{site.phone}</a></p></div><div className="mt-8 flex flex-wrap gap-3"><a href={mapSearch} {...external} className="bg-[#f26722] px-5 py-3 font-bold text-[#111110]">{t.route}</a><a href={site.googleMaps} {...external} className="border border-white/20 px-5 py-3 font-bold">{t.google}</a><a href={site.yandexMaps} {...external} className="border border-white/20 px-5 py-3 font-bold">{t.yandex}</a><a href={site.instagram} {...external} className="flex items-center gap-2 border border-white/20 px-5 py-3 font-bold"><ExternalLink size={17}/> Instagram</a></div></div><div className="relative min-h-[360px] overflow-hidden"><Image src="/images/atm-facade.jpg" alt="Star Burger facade" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover"/></div></section>
    <footer className="border-t border-white/10 px-5 py-8 text-sm text-[#a5a39c] lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Star Burger</span><a href={site.instagram} {...external}>@starburger_uz</a></div></footer><div className="fixed inset-x-0 bottom-0 z-40 flex gap-2 border-t border-white/15 bg-[#111110]/95 px-3 pb-[calc(.75rem+env(safe-area-inset-bottom))] pt-3 backdrop-blur md:hidden"><a href={site.menuUrl} {...external} className="flex min-h-12 flex-1 items-center justify-center gap-2 bg-[#f26722] px-3 py-3 text-sm font-bold text-[#111110]">{t.menu}</a><a href={site.tel} className="flex min-h-12 flex-1 items-center justify-center gap-2 bg-[#b7d33a] px-3 py-3 text-sm font-bold text-[#111110]"><Phone size={16}/> {t.contact}</a></div>
  </main>
}
