'use client';
import Image from 'next/image';
import {ArrowRight, Clock3, MapPin, Menu, Phone, ShoppingBag, X} from 'lucide-react';
import {useState} from 'react';
import {menu} from '@/lib/menu';
export default function HomePage(){const [open,setOpen]=useState(false);return <main className="min-h-screen overflow-hidden bg-[#111110] text-[#f3efe6]">
<header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#111110]/85 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#top" className="flex items-center gap-3"><Image src="/images/logo.png" alt="Star Burger" width={42} height={42} className="h-10 w-10 object-contain"/><span className="font-bold tracking-[.18em]">STAR BURGER</span></a><nav className="hidden items-center gap-8 text-sm font-semibold md:flex"><a href="#menu">Меню</a><a href="#about">О нас</a><a href="#contact">Контакты</a><a href="tel:+998905050505" className="flex items-center gap-2 text-[#b7d33a]"><Phone size={16}/> Позвонить</a></nav><button aria-label="Открыть меню" onClick={()=>setOpen(!open)} className="md:hidden">{open?<X/>:<Menu/>}</button></div>{open&&<nav className="flex flex-col gap-5 border-t border-white/10 bg-[#111110] px-5 py-6 md:hidden"><a href="#menu" onClick={()=>setOpen(false)}>Меню</a><a href="#about" onClick={()=>setOpen(false)}>О нас</a><a href="#contact" onClick={()=>setOpen(false)}>Контакты</a></nav>}</header>
<section id="top" className="relative flex min-h-[720px] items-end px-5 pb-16 pt-32 lg:min-h-[820px] lg:px-8"><Image src="/images/hero.jpg" alt="Свежий бургер Star Burger" fill priority sizes="100vw" className="img opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-[#111110] via-[#111110]/40 to-[#111110]/10"/><div className="relative mx-auto w-full max-w-7xl"><p className="mb-5 flex items-center gap-2 text-sm font-bold uppercase tracking-[.22em] text-[#b7d33a]"><span className="h-2 w-2 rounded-full bg-[#b7d33a]"/> Джизак · 24/7</p><h1 className="serif max-w-4xl text-6xl leading-[.9] tracking-[-.05em] md:text-8xl lg:text-9xl">Вкус,<br/><em className="text-[#f26722]">который</em><br/>не отпускает.</h1><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#menu" className="flex items-center justify-center gap-3 bg-[#f26722] px-6 py-4 font-bold text-[#111110] transition hover:bg-[#b7d33a]">Смотреть меню <ArrowRight size={18}/></a><a href="https://t.me/" target="_blank" rel="noreferrer" className="flex items-center justify-center gap-3 border border-white/30 px-6 py-4 font-bold hover:border-[#b7d33a]">Заказать в Telegram</a></div></div></section>
<section className="border-y border-white/10 bg-[#f3efe6] text-[#111110]"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 px-5 py-5 text-sm font-bold uppercase tracking-[.12em] lg:px-8"><span>Бургеры</span><span>Пицца</span><span>Лаваш</span><span>Гриль</span><span>Завтраки</span></div></section>
<section id="menu" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-[#b7d33a]">Из кухни</p><h2 className="serif text-5xl tracking-[-.04em] md:text-7xl">Главные хиты</h2></div><p className="max-w-sm leading-6 text-[#a5a39c]">Большие порции, свежие ингредиенты и тот самый вкус, ради которого возвращаются.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{menu.map((item,i)=><article key={item.name} className={`group ${i===0?'sm:col-span-2 lg:col-span-2':''}`}><div className="relative aspect-[4/3] overflow-hidden bg-[#252523]"><Image src={item.image} alt={item.name} fill sizes="(max-width: 640px) 100vw, 50vw" className="img transition duration-500 group-hover:scale-105"/><span className="absolute left-3 top-3 bg-[#b7d33a] px-3 py-1 text-xs font-black uppercase text-[#111110]">Хит</span></div><div className="flex items-start justify-between gap-3 border-b border-white/15 py-4"><div><h3 className="text-xl font-bold">{item.name}</h3><p className="mt-1 text-sm text-[#a5a39c]">{item.desc}</p></div><strong className="whitespace-nowrap text-[#f26722]">{item.price}</strong></div></article>)}</div></section>
<section id="about" className="bg-[#b7d33a] px-5 py-20 text-[#111110] lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_1.2fr] lg:items-end"><div><p className="mb-3 text-sm font-black uppercase tracking-[.2em]">Почему Star Burger</p><h2 className="serif text-5xl leading-none tracking-[-.04em] md:text-7xl">Ночная смена<br/>всегда открыта.</h2></div><div className="grid gap-6 sm:grid-cols-3"><div><Clock3 size={27}/><h3 className="mt-4 text-lg font-bold">24/7</h3><p className="mt-2 text-sm leading-5">Когда бы ни захотелось — мы готовим.</p></div><div><ShoppingBag size={27}/><h3 className="mt-4 text-lg font-bold">С собой</h3><p className="mt-2 text-sm leading-5">Упакуем горячим, чтобы донести вкус.</p></div><div><MapPin size={27}/><h3 className="mt-4 text-lg font-bold">В Джизаке</h3><p className="mt-2 text-sm leading-5">Заглядывайте всей компанией.</p></div></div></div></section>
<section id="contact" className="mx-auto grid max-w-7xl gap-8 px-5 py-20 lg:grid-cols-2 lg:px-8 lg:py-28"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-[#b7d33a]">Заезжайте</p><h2 className="serif text-5xl tracking-[-.04em] md:text-7xl">До встречи<br/>за столом.</h2><div className="mt-8 space-y-4 text-[#a5a39c]"><p className="flex gap-3"><MapPin className="text-[#f26722]"/> Джизак, Узбекистан</p><p className="flex gap-3"><Clock3 className="text-[#f26722]"/> Открыты круглосуточно</p></div></div><div className="relative min-h-[360px] overflow-hidden"><Image src="/images/atm-facade.jpg" alt="Фасад Star Burger вечером" fill sizes="(max-width: 1024px) 100vw, 50vw" className="img"/><div className="absolute inset-0 flex items-end bg-gradient-to-t from-[#111110]/75 to-transparent p-6"><a href="https://maps.google.com" target="_blank" rel="noreferrer" className="flex items-center gap-2 bg-[#f26722] px-5 py-3 font-bold text-[#111110]">Построить маршрут <ArrowRight size={18}/></a></div></div></section>
<footer className="border-t border-white/10 px-5 py-8 text-sm text-[#a5a39c] lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Star Burger</span><span>Сделано с аппетитом в Джизаке</span></div></footer><div className="fixed inset-x-0 bottom-0 z-40 flex border-t border-white/15 bg-[#111110]/95 p-3 backdrop-blur md:hidden"><a href="#menu" className="flex flex-1 items-center justify-center gap-2 bg-[#f26722] py-3 font-bold text-[#111110]">Меню</a><a href="tel:+998905050505" className="flex flex-1 items-center justify-center gap-2 bg-[#b7d33a] py-3 font-bold text-[#111110]">Позвонить</a></div></main>}
