'use client'
import Image from 'next/image'
import {ArrowRight,Clock3,ExternalLink,MapPin,Menu as MenuIcon,MessageCircle,Phone,Users,X} from 'lucide-react'
import {track} from '@vercel/analytics'
import {useEffect,useState} from 'react'
import {copy,gallery,menu,site,type Locale} from '@/lib/site-data'
import siteConfig from '@/lib/site-config'
const ext={target:'_blank',rel:'noopener noreferrer' as const}

export default function HomePage({locale='uz'}:{locale?:Locale}){
 const [open,setOpen]=useState(false),t=copy[locale]
 useEffect(()=>{document.documentElement.lang=t.lang},[t.lang])
 const ev=(name:string)=>()=>track(name,{locale})
 const schema={'@context':'https://schema.org','@type':'Restaurant',name:'Star Burger',image:siteConfig.ogImage,url:`${siteConfig.siteUrl}/${locale}`,address:{'@type':'PostalAddress',streetAddress:siteConfig.address,addressLocality:'Jizzax',addressCountry:'UZ'},telephone:siteConfig.tel.replace('tel:',''),openingHours:'Mo-Su 00:00-24:00',priceRange:'$$',servesCuisine:['Burgers','Pizza','Turkish','Grill'],sameAs:[site.googleMaps,site.yandexMaps,site.telegram,site.instagram]}
 return <main className="shell pb-20 md:pb-0"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <header className="nav"><div className="wrap flex items-center justify-between py-4"><a href="#top" className="brand"><span className="logo"><Image src="/images/logo.png" alt="Star Burger" width={44} height={44}/></span><b>STAR BURGER</b></a><nav className="hidden gap-8 text-sm font-semibold md:flex"><a href="#menu">{t.menu}</a><a href="#story">{t.about}</a><a href="#reviews">{t.reviews}</a><a href="#contact">{t.contact}</a></nav><div className="flex items-center gap-2"><div className="langs" aria-label={t.language}>{(['uz','ru','en'] as Locale[]).map(l=><a key={l} href={`/${l}`} className={l===locale?'on':''}>{l.toUpperCase()}</a>)}</div><button className="icon md:hidden" aria-label={open?t.closeMenu:t.openMenu} onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</button></div></div>{open&&<nav className="mobile md:hidden">{[['#menu',t.menu],['#story',t.about],['#reviews',t.reviews],['#contact',t.contact]].map(([h,l])=><a key={h} href={h} onClick={()=>setOpen(false)}>{l}<ArrowRight size={17}/></a>)}</nav>}</header>

 <section id="top" className="hero"><Image src="/images/food-burger.jpg" alt={t.heroAlt} fill priority sizes="100vw" className="hero-img"/><div className="veil"/><div className="orb one"/><div className="orb two"/><div className="noise"/><div className="wrap hero-inner"><div className="max-w-4xl"><p className="eyebrow"><i/>{t.city}</p><h1>{t.hero[0]}<br/><em>{t.hero[1]}</em> {t.hero[2]}</h1><p className="lead">{t.intro}</p><div className="actions"><a href={site.menuUrl} {...ext} onClick={ev('menu_open')} className="primary">{t.viewMenu}<ArrowRight size={18}/></a><a href={site.telegramOrderBot} {...ext} onClick={ev('telegram_order_click')} className="ghost"><MessageCircle size={18}/>{t.order}</a></div></div><div className="stamp"><small>STAR</small><strong>24/7</strong><small>JIZZAX</small></div></div><div className="ticker"><div>{[...t.categories,...t.categories].map((x,i)=><span key={i}>{x}<b>✦</b></span>)}</div></div></section>

 <section id="menu" className="paper section"><div className="wrap"><div className="heading"><div><p className="eyebrow ink">{t.kitchen}</p><h2>{t.hits}</h2></div><a href={site.menuUrl} {...ext} onClick={ev('full_menu_click')} className="link">{t.fullMenu}<ArrowRight size={17}/></a></div><div className="cards">{menu.map((m,i)=><article key={m.name} className="card"><a href={site.telegramOrderBot} {...ext} onClick={ev('dish_order_click')}><div className="photo"><Image src={m.image} alt={m.name} fill sizes="(max-width:768px) 100vw,33vw" className="object-cover"/><span>0{i+1}</span><b>{i===0?t.signature:t.chefPick}</b></div><div className="card-copy"><div><h3>{m.name}</h3><p>{m.desc[locale]}</p></div><strong>{m.price}<small> UZS</small></strong></div></a></article>)}</div></div></section>

 <section id="story" className="story"><div className="noise"/><div className="wrap story-grid"><div><p className="eyebrow">{t.about}</p><h2>{t.always}</h2><p className="story-lead">{t.experienceText}</p></div><div className="features"><div><Clock3/><small>01</small><h3>24/7</h3><p>{t.open}</p></div><div><Users/><small>02</small><h3>{t.private}</h3><p>{t.privateText}</p></div><div><MessageCircle/><small>03</small><h3>{t.football}</h3><p>{t.footballText}</p></div></div></div></section>

 <section className="paper section"><div className="wrap"><p className="eyebrow ink">{t.atmosphereLabel}</p><h2>{t.atmosphere}</h2><div className="gallery">{gallery.map(([src,alt],i)=><figure key={src} className={`g g${i+1}`}><Image src={src} alt={alt} fill loading="lazy" sizes="(max-width:768px) 100vw,50vw" className="object-cover"/><span>0{i+1}</span></figure>)}</div></div></section>

 <section id="reviews" className="reviews"><div className="wrap review-grid"><div><p className="eyebrow">{t.reviewsLabel}</p><h2>{t.reviewsHeadline}</h2></div><div><p>{t.reviewsText}</p><div className="actions"><a href={site.googleReviews} {...ext} onClick={ev('google_reviews_click')} className="outline">Google<ExternalLink size={15}/></a><a href={site.yandexReviews} {...ext} onClick={ev('yandex_reviews_click')} className="outline">Yandex<ExternalLink size={15}/></a></div></div></div></section>

 <section id="contact" className="paper contact"><div className="wrap contact-grid"><div className="contact-copy"><p className="eyebrow ink">{t.findLabel}</p><h2>{t.find}</h2><div className="contact-list"><p><MapPin/>{t.address}</p><p><Clock3/>{t.open}</p><a href={site.tel} onClick={ev('phone_click')}><Phone/>{site.phone}</a></div><div className="actions"><a href={site.mapSearch} {...ext} onClick={ev('directions_click')} className="dark">{t.route}<ArrowRight size={17}/></a><a href={site.instagram} {...ext} onClick={ev('instagram_click')} className="light">Instagram<ExternalLink size={15}/></a></div></div><div className="contact-photo"><Image src="/images/atm-facade.jpg" alt={t.facadeAlt} fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/></div></div></section>
 <footer><div className="wrap foot"><span>STAR BURGER</span><small>© 2026 · Jizzax · 24/7</small></div></footer>
 <div className="mobile-actions md:hidden"><a href={site.menuUrl} {...ext} onClick={ev('mobile_menu_click')}>{t.menu}</a><a href={site.telegramOrderBot} {...ext} onClick={ev('mobile_order_click')}>{t.orderBot}</a></div>
 </main>
}
